| **Inicio** | **atrás 20** | **Siguiente 22** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./20.Busqueda_y_Filtrado.ipynb)| [⏩](./22.Union_y_Separacion.ipynb)|

# **21. Numpy: Agregación y Ejes de Arrays (arreglos) para Procesar Datos**

## **Introducción a los Ejes y Funciones de Agregación**

En NumPy, un eje es una dimensión de un arreglo. Para entender mejor los ejes, es útil pensar en un arreglo multidimensional como una tabla con filas y columnas. Las filas corresponden a la primera dimensión del arreglo y las columnas corresponden a la segunda dimensión. En general, un arreglo multidimensional puede tener cualquier número de dimensiones, y cada dimensión se puede considerar como un eje.

Las funciones de agregación en NumPy son funciones que realizan cálculos estadísticos sobre los elementos de un arreglo. Estas funciones se pueden aplicar a lo largo de uno o más ejes del arreglo. Algunas de las funciones de agregación más comunes en NumPy son:

* `np.sum`: devuelve la suma de los elementos del arreglo.
* `np.mean`: devuelve la media de los elementos del arreglo.
* `np.min`: devuelve el valor mínimo del arreglo.
* `np.max`: devuelve el valor máximo del arreglo.
* `np.std`: devuelve la desviación estándar de los elementos del arreglo.
* `np.var`: devuelve la varianza de los elementos del arreglo.

A continuación, se presenta un ejemplo de cómo utilizar una función de agregación en un arreglo de NumPy:

In [1]:
import numpy as np

# Crear un arreglo de 2 dimensiones con valores aleatorios
a = np.random.rand(3, 4)
print("Arreglo original:")
print(a)

# Calcular la suma de los elementos de cada fila del arreglo
suma_filas = np.sum(a, axis=1)
print("Suma de los elementos de cada fila:")
print(suma_filas)

# Calcular el valor mínimo de cada columna del arreglo
min_columnas = np.min(a, axis=0)
print("Valor mínimo de cada columna:")
print(min_columnas)

Arreglo original:
[[0.54775122 0.56971291 0.40298929 0.10532938]
 [0.44638613 0.52342213 0.22594107 0.14230966]
 [0.79128394 0.83902178 0.48837483 0.86117661]]
Suma de los elementos de cada fila:
[1.6257828  1.33805899 2.97985717]
Valor mínimo de cada columna:
[0.44638613 0.52342213 0.22594107 0.10532938]


## **Función de agregación: min, max, argmin, argmax, sum y mean**

In [2]:
import numpy as np

# Crear un arreglo de 1 dimensión
a = np.array([2, 5, 3, 9, 1])
print("Arreglo original:")
print(a)

# Calcular el valor mínimo del arreglo
minimo = np.min(a)
print("Valor mínimo del arreglo:", minimo)

# Calcular el índice del valor mínimo del arreglo
indice_minimo = np.argmin(a)
print("Índice del valor mínimo del arreglo:", indice_minimo)

# Calcular la suma de los elementos del arreglo
suma = np.sum(a)
print("Suma de los elementos del arreglo:", suma)

# Calcular la media de los elementos del arreglo
media = np.mean(a)
print("Media de los elementos del arreglo:", media)

# Crear un arreglo de 2 dimensiones con valores aleatorios
b = np.random.rand(3, 4)
print("Arreglo original:")
print(b)

# Calcular el valor máximo de cada columna del arreglo
maximo_columnas = np.max(b, axis=0)
print("Valor máximo de cada columna:")
print(maximo_columnas)

# Calcular el índice del valor máximo de cada fila del arreglo
indice_maximo_filas = np.argmax(b, axis=1)
print("Índice del valor máximo de cada fila:")
print(indice_maximo_filas)

Arreglo original:
[2 5 3 9 1]
Valor mínimo del arreglo: 1
Índice del valor mínimo del arreglo: 4
Suma de los elementos del arreglo: 20
Media de los elementos del arreglo: 4.0
Arreglo original:
[[0.87161539 0.54624888 0.2391306  0.13630239]
 [0.72293875 0.42556439 0.26566611 0.79316407]
 [0.85955204 0.16635461 0.10812559 0.92643666]]
Valor máximo de cada columna:
[0.87161539 0.54624888 0.26566611 0.92643666]
Índice del valor máximo de cada fila:
[0 3 3]


## **Función de agregación por Eje (Axis)**

In [3]:
import numpy as np

# Crear un arreglo de 2 dimensiones con valores aleatorios
a = np.random.randint(1, 10, size=(3, 4))
print("Arreglo original:")
print(a)

# Calcular el valor máximo de cada fila del arreglo
maximo_filas = np.max(a, axis=1)
print("Valor máximo de cada fila:")
print(maximo_filas)

# Calcular el valor mínimo de cada columna del arreglo
minimo_columnas = np.min(a, axis=0)
print("Valor mínimo de cada columna:")
print(minimo_columnas)

# Calcular la suma de todos los elementos del arreglo
suma_total = np.sum(a)
print("Suma total de todos los elementos del arreglo:", suma_total)

# Calcular la media de cada fila del arreglo
media_filas = np.mean(a, axis=1)
print("Media de cada fila:")
print(media_filas)

Arreglo original:
[[5 5 1 7]
 [3 8 1 4]
 [9 1 7 1]]
Valor máximo de cada fila:
[7 8 9]
Valor mínimo de cada columna:
[3 1 1 1]
Suma total de todos los elementos del arreglo: 52
Media de cada fila:
[4.5 4.  4.5]


| **Inicio** | **atrás 20** | **Siguiente 22** |
|----------- |-------------- |---------------|
| [🏠](../../README.md) | [⏪](./20.Busqueda_y_Filtrado.ipynb)| [⏩](./22.Union_y_Separacion.ipynb)|